openapi: 3.0.3
info:
  title: API Clean Bajoqueta
  description: ""
  contact:
    email: pepegascobule@gmail.com
  version: 1.0.11
servers:
- url: /
tags:
- name: Mediciones
  description: Metodos para trabajar con las mediciones
paths:
  /mediciones/guardar_mediciones:
    post:
      tags:
      - Mediciones
      summary: Añade un nueva medicion a la base de datos
      description: Añade un nueva medicion a la base de datos
      operationId: addMed
      requestBody:
        description: Añade un nueva medicion a la base de datos
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/setMedicion'
          application/xml:
            schema:
              $ref: '#/components/schemas/setMedicion'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/setMedicion'
        required: true
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/setMedicion'
            application/xml:
              schema:
                $ref: '#/components/schemas/setMedicion'
        "405":
          description: Invalid input
      x-swagger-router-controller: Mediciones
  /mediciones/recuperar_medicions:
    get:
      tags:
      - Mediciones
      summary: Recoger mediciones guardadas
      description: Recoger mediciones guardadas
      operationId: getMed
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/getMedicion'
                x-content-type: application/json
            application/xml:
              schema:
                type: array
                xml:
                  name: medicion
                items:
                  $ref: '#/components/schemas/getMedicion'
        "400":
          description: Invalid status value
      x-swagger-router-controller: Mediciones
components:
  schemas:
    setMedicion:
      required:
      - idContaminante
      - instante
      - latitud
      - longitud
      - valor
      type: object
      properties:
        id:
          type: integer
          example: 10
        idContaminante:
          type: integer
          example: 2
        instante:
          type: string
        valor:
          type: number
          format: float
        latitud:
          type: number
          format: float
        longitud:
          type: number
          format: float
        temperatura:
          type: number
          format: float
      example:
        idContaminante: 1
        instante: 24/08/2023
        valor: 123
        latitud: 4
        longitud: 3
        temperatura: 20
      xml:
        name: medicion
    getMedicion:
      required:
      - id
      - idContaminante
      - instante
      - latitud
      - longitud
      - valor
      type: object
      properties:
        id:
          type: integer
          example: 10
        idContaminante:
          type: integer
          example: 2
        instante:
          type: string
        valor:
          type: number
          format: float
        latitud:
          type: number
          format: float
        longitud:
          type: number
          format: float
        temperatura:
          type: number
          format: float
      example:
        id: 10
        idContaminante: 1
        instante: 24/08/2023
        valor: 123
        latitud: 4
        longitud: 3
        temperatura: 20
      xml:
        name: medicion
