openapi: 3.0.3
info:
  title: API Clean Bajoqueta
  description: ""
  contact:
    email: pepegascobule@gmail.com
  version: 1.0.11
servers:
  - url: /
tags:
  - name: Mediciones
    description: Metodos para trabajar con las mediciones
  - name: User
    description: Metodo para trabajar con los usuarios
paths:
  /mediciones/guardar_mediciones:
    post:
      tags:
        - Mediciones
      summary: Añade un nueva medicion a la base de datos
      description: Añade un nueva medicion a la base de datos
      operationId: addMed
      requestBody:
        description: Añade un nueva medicion a la base de datos
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/setMedicion"
          application/xml:
            schema:
              $ref: "#/components/schemas/setMedicion"
          application/x-www-form-urlencoded:
            schema:
              $ref: "#/components/schemas/setMedicion"
        required: true
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/setMedicion"
            application/xml:
              schema:
                $ref: "#/components/schemas/setMedicion"
        "400":
          description: Invalid input
      x-swagger-router-controller: Mediciones
  /mediciones/generar_mediciones:
    post:
      tags:
        - Mediciones
      summary: Genera 100 mediciones alrededor de la universidad
      description: Genera 100 mediciones alrededor de la universidad
      operationId: fakeMed
      responses:
        "200":
          description: Successful operation
        "400":
          description: Error al crear las mediciones.
      x-swagger-router-controller: Mediciones
  /mediciones/recuperar_medicions/{limit}:
    get:
      tags:
        - Mediciones
      summary: Recoger mediciones guardadas
      description: Recoger mediciones guardadas
      operationId: getMed
      parameters:
        - name: email
          in: header
          required: true
          style: simple
          explode: false
          schema:
            type: string
            format: email
          example: email@email.com
        - name: limit
          in: path
          required: true
          style: simple
          explode: false
          schema:
            type: integer
          example: 100
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/getMedicion"
                x-content-type: application/json
            application/xml:
              schema:
                type: array
                xml:
                  name: medicion
                items:
                  $ref: "#/components/schemas/getMedicion"
        "400":
          description: Invalid status value
      x-swagger-router-controller: Mediciones
  /mediciones/mediciones_zona:
    get:
      tags:
        - Mediciones
      summary: Recoger mediciones en una zona en especifico
      description: Recoger mediciones en una zona en especifico
      operationId: getMedZone
      parameters:
        - name: latitud
          in: query
          required: true
          schema:
            type: string
          example: 38.995593
        - name: longitud
          in: query
          required: true
          schema:
            type: string
          example: -0.167132
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/getMedicion"
                x-content-type: application/json
            application/xml:
              schema:
                type: array
                xml:
                  name: medicion
                items:
                  $ref: "#/components/schemas/getMedicion"
        "400":
          description: Invalid status value
      x-swagger-router-controller: Mediciones

  /user/getUserByEmail:
    get:
      tags:
        - User
      summary: Comprobar si usuario existe
      description: Comprobar si usuario existe
      operationId: getUser
      parameters:
        - name: email
          in: header
          required: true
          style: simple
          explode: false
          schema:
            type: string
            format: email
      responses:
        "200":
          description: Se ha encontrado un registro
          content:
            applicaction/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/user"
                x-content-type: applicaction/json
            application/xml:
              schema:
                type: array
                xml:
                  name: user
                items:
                  $ref: "#/components/schemas/user"
        "400":
          description: Error al buscar usuarios. Contacte con un administrador
      x-swagger-router-controller: User
  /user/insertUser:
    post:
      tags:
        - User
      summary: Insertar nuevo usuario
      description: Añade un nuevo usuario a la base de datos
      operationId: insertUser
      requestBody:
        description: Añade un nuevo usuario a la base de datos
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/user"
          application/xml:
            schema:
              $ref: "#/components/schemas/user"
          application/x-www-form-urlencoded:
            schema:
              $ref: "#/components/schemas/user"
        required: true
      responses:
        "200":
          description: Usuario Insertado
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/user"
            application/xml:
              schema:
                $ref: "#/components/schemas/user"
        "400":
          description: Error al insertar usuarios. Contacte con un administrador
      x-swagger-router-controller: User
  /user/updateUserByEmail:
    put:
      tags:
        - User
      summary: Actualizar un usuario ya creado
      description: Actualizar un usuario ya creado
      operationId: updateUser
      parameters:
        - name: email
          in: header
          required: true
          style: simple
          explode: false
          schema:
            type: string
            format: email
      requestBody:
        description: Actualizar un usuario ya creado
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/user"
          application/xml:
            schema:
              $ref: "#/components/schemas/user"
          application/x-www-form-urlencoded:
            schema:
              $ref: "#/components/schemas/user"
        required: true
      responses:
        "200":
          description: Usuario actualizado
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/user"
            application/xml:
              schema:
                $ref: "#/components/schemas/user"
        "400":
          description: Error al actualizar usuarios. Contacte con un administrador
      x-swagger-router-controller: User
  /user/deleteByEmail:
    delete:
      tags:
        - User
      summary: Eliminar usuario filtrado por ID
      description: Eliminar usuario filtrado por ID
      operationId: deleteUser
      parameters:
        - name: email
          in: header
          required: true
          style: simple
          explode: false
          schema:
            type: string
            format: email
      responses:
        "200":
          description: Se ha eliminado un registro
        "400":
          description: Error al eliminar usuarios. Contacte con un administrador
      x-swagger-router-controller: User
components:
  schemas:
    setMedicion:
      required:
        - idContaminante
        - idSonda
        - emailUser
        - instante
        - latitud
        - longitud
        - valor
      type: object
      properties:
        id:
          type: integer
          example: 10
        idContaminante:
          type: integer
          example: 2
        idSonda:
          type: integer
          example: 5
        emailUser:
          type: string
          example: email@email.com
        instante:
          type: string
        valor:
          type: number
          format: float
        latitud:
          type: number
          format: float
        longitud:
          type: number
          format: float
        temperatura:
          type: number
          format: float
      example:
        idContaminante: 4
        idSonda: 5
        emailUser: email@email.com
        instante: 24/08/2023
        valor: 123
        latitud: 4
        longitud: 3
        temperatura: 20
      xml:
        name: medicion
    getMedicion:
      required:
        - email
        - limit
      type: object
      properties:
        id:
          type: integer
          example: 10
        idContaminante:
          type: integer
          example: 2
        instante:
          type: string
        valor:
          type: number
          format: float
        latitud:
          type: number
          format: float
        longitud:
          type: number
          format: float
        temperatura:
          type: number
          format: float
        email:
          type: number
          format: float
        limit:
          type: integer
          example: 50
      example:
        id: 10
        idContaminante: 4
        instante: 24/08/2023
        valor: 123
        latitud: 4
        longitud: 3
        temperatura: 20
      xml:
        name: medicion
    user:
      type: object
      properties:
        email:
          type: string
          format: email
        contraseña:
          type: string
          format: password
        rol:
          type: integer
        nombreApellido:
          type: string
        imagen:
          type: string
        verificado:
          type: integer
        token:
          type: string
        telefono:
          type: string
      example:
        email: email@email.com
        contraseña: esternocleidomastoideo
        rol: 1
        nombreApellido: Jhon Doe
        imagen: "Imagen"
        verificado: 1
        telefono: "123456789"
